# Generated by Django 4.2 on 2023-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_artigo_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cadeira', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
